---
title: 'Biostatistics Task 3'
author: 'Danyu Zhang & Daniel Alonso'
date: 'May 28th, 2021'
output: 'pdf_document'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
collapse = TRUE,
comment = '#>',
fig.path = './figures/'
)
knitr::knit_engines$set(julia = JuliaCall::eng_juliacall)
options(JULIA_HOME = '/home/dreth/julia/bin')
```

```{r, echo=TRUE, warning=FALSE, message=FALSE}
library(survival)
library(ggplot2)
library(nlme)
library(SASmixed)
```

# Exercise 1

```{r, echo=FALSE, warning=FALSE, message=FALSE}
data(PBIB)
pbib <- PBIB
```

## Fitting a model with random effects

```{r, echo=FALSE, warning=FALSE, message=FALSE}
lme(response~Treatment, random=~Treatment|Block, data=pbib)
```


# Exercise 2

```{r, echo=FALSE, warning=FALSE, message=FALSE}
data(Oxide)
oxide <- Oxide
```


# Exercise 3

```{r, echo=FALSE, warning=FALSE, message=FALSE}
data(Cultivation)
cultivation <- Cultivation
```


# Exercise 4

```{r, echo=FALSE, warning=FALSE, message=FALSE}
maths <- read.table('./maths.txt', header=TRUE)
```


# Exercise 5

```{r, echo=FALSE, warning=FALSE, message=FALSE}
eating <- read.table('./eating.txt', header=TRUE)
```


